/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex02;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ViewFrameForm extends javax.swing.JFrame {

    private List<Admin> admins = new ArrayList<>();
    private Dao dao;
    private LoginSuccess lg;
    private DialogMessage dialogMessage;

    public ViewFrameForm() {
        initComponents();
        initComponentsManually();
        initEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        lbBackround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setPreferredSize(new java.awt.Dimension(70, 25));
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 260, 42));
        getContentPane().add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 272, 260, 42));

        btLogin.setBackground(new java.awt.Color(255, 51, 0));
        btLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("LOGIN");
        btLogin.setFocusPainted(false);
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 375, 260, 40));

        btExit.setBackground(new java.awt.Color(255, 51, 0));
        btExit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("X");
        btExit.setFocusPainted(false);
        getContentPane().add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 58, 58));

        lbBackround.setBackground(new java.awt.Color(255, 51, 0));
        lbBackround.setForeground(new java.awt.Color(255, 255, 255));
        lbBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/convenient-login-form.jpg"))); // NOI18N
        getContentPane().add(lbBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFrameForm().setVisible(true);
            }
        });
    }

    private void initComponentsManually() {
        setLocationRelativeTo(null);
    }

    private void initEvents() {
        btExitEvents();
        btLoginEvents();
    }

    private void btLoginEvents() {
        dao = new Dao();
        admins = dao.getAll();
        btLogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                admins.forEach(System.out::println);
                for (int i = 0; i < admins.size(); i++) {
                    if (tfUsername.getText().equals(admins.get(i).getUsername())
                            && pfPassword.getText().equals(admins.get(i).getPassword())) {
                        lg = new LoginSuccess();
                        lg.setVisible(true);
                        break;
                    }
                    if (i == admins.size() - 1 && (!tfUsername.getText().equals(admins.get(i).getUsername())
                            || !pfPassword.getText().equals(admins.get(i).getPassword()))) {
                        dialogMessage = new DialogMessage();
                        JOptionPane.showMessageDialog(dialogMessage, "Sai Username hoặc Password, nhập lại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                        tfUsername.setText("");
                        pfPassword.setText("");
                        tfUsername.requestFocus();
                    }
                }
            }

        });
    }

    private void btExitEvents() {
        btExit.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ViewFrameForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.exit(0);
            }

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel lbBackround;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

}
