/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Container;
import java.util.Date;

/**
 *
 * @author qphan
 */
public class Ex05 extends javax.swing.JFrame {

   
    private final Container conn = getContentPane();
    
    public Ex05() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
        conn.setBackground(Color.BLACK);
        
        dcStart.setDate(new Date());
        dcEnd.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbMale = new javax.swing.JLabel();
        tfMale = new javax.swing.JTextField();
        lbMailError = new javax.swing.JLabel();
        btLike = new javax.swing.JButton();
        lbFemale = new javax.swing.JLabel();
        tfFemale = new javax.swing.JTextField();
        lbFemaleError = new javax.swing.JLabel();
        btLove = new javax.swing.JButton();
        lbStart = new javax.swing.JLabel();
        lbEnd = new javax.swing.JLabel();
        lbResult = new javax.swing.JLabel();
        dcStart = new com.toedter.calendar.JDateChooser();
        dcEnd = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 0, 204));
        lbTitle.setText("Love Time Application");

        lbMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMale.setForeground(new java.awt.Color(255, 255, 255));
        lbMale.setText("Người thứ nhất");

        lbMailError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMailError.setForeground(new java.awt.Color(255, 0, 51));
        lbMailError.setText("Chưa nhập tên");

        btLike.setIcon(new javax.swing.ImageIcon("D:\\home\\workspace\\class\\j4t-java06-swing\\Lesson18\\src\\main\\java\\images\\48px_like.png")); // NOI18N

        lbFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbFemale.setForeground(new java.awt.Color(255, 255, 255));
        lbFemale.setText("Người thứ hai");

        lbFemaleError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFemaleError.setForeground(new java.awt.Color(255, 0, 51));
        lbFemaleError.setText("Chưa nhập tên");

        btLove.setIcon(new javax.swing.ImageIcon("D:\\home\\workspace\\class\\j4t-java06-swing\\Lesson18\\src\\main\\java\\images\\48px_love.png")); // NOI18N

        lbStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStart.setForeground(new java.awt.Color(255, 255, 255));
        lbStart.setText("Ngày bắt đầu");

        lbEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbEnd.setForeground(new java.awt.Color(255, 255, 255));
        lbEnd.setText("Ngày kết thúc");

        lbResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResult.setForeground(new java.awt.Color(255, 255, 255));
        lbResult.setText("Kết quả: ");

        dcStart.setDateFormatString("dd/MM/yyyy");

        dcEnd.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMale)
                    .addComponent(tfMale, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMailError)
                    .addComponent(btLike))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lbStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lbEnd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFemale)
                    .addComponent(tfFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFemaleError)
                    .addComponent(btLove))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lbResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMale)
                    .addComponent(lbFemale))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfMale, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStart)
                    .addComponent(tfFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMailError)
                    .addComponent(lbFemaleError)
                    .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btLike)
                    .addComponent(lbEnd)
                    .addComponent(btLove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lbResult)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLike;
    private javax.swing.JButton btLove;
    private com.toedter.calendar.JDateChooser dcEnd;
    private com.toedter.calendar.JDateChooser dcStart;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbFemale;
    private javax.swing.JLabel lbFemaleError;
    private javax.swing.JLabel lbMailError;
    private javax.swing.JLabel lbMale;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField tfFemale;
    private javax.swing.JTextField tfMale;
    // End of variables declaration//GEN-END:variables
}
