/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import utils.ImageUtils;

/**
 *
 * @author Administrator
 */
public class FrameNotepad extends javax.swing.JFrame {

    /**
     * Creates new form FrNotepad
     */
    public FrameNotepad() {
        initComponents();
        
        setIconImage(ImageUtils.load(getClass().getResource("/images/msg-ok.gif").getPath()));
        this.setLocationRelativeTo(null);
        this.setSize(680, 330);
        initComps();
    }
    
    private void initComps() {
        JPopupMenu popFile = new JPopupMenu();
        
        JMenuItem mniOpen = new JMenuItem("Open");
        popFile.add(mniOpen);
        
        JMenuItem mniSave = new JMenuItem("Save");
        popFile.add(mniSave);
        
        JMenu mnOpenRecentFiles = new JMenu("Open recent files");
        popFile.add(mnOpenRecentFiles);
        
        JMenuItem mniStudentApp = new JMenuItem("Student App");
        JMenuItem mniLectureApp = new JMenuItem("Lecture App");
        
        mnOpenRecentFiles.add(mniStudentApp);
        mnOpenRecentFiles.add(mniLectureApp);
        
        JMenuItem mniExit = new JMenuItem("Exit");
        popFile.add(mniExit);
        
        taNotepad.setComponentPopupMenu(popFile);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pnTextArea = new javax.swing.JPanel();
        scrollTextArea = new javax.swing.JScrollPane();
        taNotepad = new javax.swing.JTextArea();
        pnToolBar = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        btSaveAs = new javax.swing.JButton();
        btZoomIn = new javax.swing.JButton();
        btZoomOut = new javax.swing.JButton();
        nmbNote = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mniOpen = new javax.swing.JMenuItem();
        mniSave = new javax.swing.JMenuItem();
        mnOpenRecentFiles = new javax.swing.JMenu();
        mnStudent = new javax.swing.JMenuItem();
        mnLecture = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnEdit = new javax.swing.JMenu();
        mnHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnTextArea.setLayout(new java.awt.BorderLayout());

        taNotepad.setColumns(20);
        taNotepad.setRows(5);
        scrollTextArea.setViewportView(taNotepad);

        pnTextArea.add(scrollTextArea, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnTextArea, java.awt.BorderLayout.CENTER);

        pnToolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btSaveAs.setText("Save as");
        btSaveAs.setFocusable(false);
        btSaveAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSaveAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btSaveAs);

        btZoomIn.setText("Zoom In");
        btZoomIn.setFocusable(false);
        btZoomIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btZoomIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btZoomIn);

        btZoomOut.setText("Zoom Out");
        btZoomOut.setFocusable(false);
        btZoomOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btZoomOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btZoomOut);

        pnToolBar.add(toolbar);

        getContentPane().add(pnToolBar, java.awt.BorderLayout.NORTH);

        mnFile.setText("File");

        mniOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        mniOpen.setText("Open");
        mnFile.add(mniOpen);

        mniSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editor.png"))); // NOI18N
        mniSave.setText("Save");
        mnFile.add(mniSave);

        mnOpenRecentFiles.setText("Open recent files");

        mnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_adv.png"))); // NOI18N
        mnStudent.setText("Student App");
        mnOpenRecentFiles.add(mnStudent);

        mnLecture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        mnLecture.setText("Lecture App");
        mnOpenRecentFiles.add(mnLecture);

        mnFile.add(mnOpenRecentFiles);
        mnFile.add(jSeparator2);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power_off.png"))); // NOI18N
        mniExit.setText("Exit");
        mnFile.add(mniExit);

        nmbNote.add(mnFile);

        mnEdit.setText("Edit");
        nmbNote.add(mnEdit);

        mnHelp.setText("Help");
        nmbNote.add(mnHelp);

        setJMenuBar(nmbNote);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNotepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSaveAs;
    private javax.swing.JButton btZoomIn;
    private javax.swing.JButton btZoomOut;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnLecture;
    private javax.swing.JMenu mnOpenRecentFiles;
    private javax.swing.JMenuItem mnStudent;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenuItem mniSave;
    private javax.swing.JMenuBar nmbNote;
    private javax.swing.JPanel pnTextArea;
    private javax.swing.JPanel pnToolBar;
    private javax.swing.JScrollPane scrollTextArea;
    private javax.swing.JTextArea taNotepad;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
