/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.date02;

/**
 *
 * @author PC
 */
public class Ex05 extends javax.swing.JFrame {

    /**
     * Creates new form Ex05
     */
    public Ex05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTeamDT = new javax.swing.JLabel();
        lbTeamG = new javax.swing.JLabel();
        lbTeamVL = new javax.swing.JLabel();
        btStart = new javax.swing.JButton();
        lbBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Võ Lâm Truyền Kì 3D");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTeamDT.setIcon(new javax.swing.ImageIcon("E:\\GiaoTrinhHocTap\\Java\\java06-swing\\lesson18_BaiTap_Nhom4\\src\\main\\java\\image\\VoLamTruyenKi\\Biểu Tượng Ashe Mini.jpg")); // NOI18N
        getContentPane().add(lbTeamDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 240, 160));

        lbTeamG.setIcon(new javax.swing.ImageIcon("E:\\GiaoTrinhHocTap\\Java\\java06-swing\\lesson18_BaiTap_Nhom4\\src\\main\\java\\image\\VoLamTruyenKi\\Biểu Tượng Evelynn Mini.jpg")); // NOI18N
        getContentPane().add(lbTeamG, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 220, 140));

        lbTeamVL.setIcon(new javax.swing.ImageIcon("E:\\GiaoTrinhHocTap\\Java\\java06-swing\\lesson18_BaiTap_Nhom4\\src\\main\\java\\image\\VoLamTruyenKi\\Biểu Tượng Alistar Mini.jpg")); // NOI18N
        getContentPane().add(lbTeamVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 240, 150));

        btStart.setIcon(new javax.swing.ImageIcon("E:\\GiaoTrinhHocTap\\Java\\java06-swing\\VoLamTruyenKi\\start.jpg")); // NOI18N
        btStart.setAlignmentY(0.0F);
        btStart.setMaximumSize(new java.awt.Dimension(100, 100));
        btStart.setMinimumSize(new java.awt.Dimension(100, 100));
        btStart.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(btStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 100, 100));

        lbBackgroundImage.setIcon(new javax.swing.ImageIcon("E:\\GiaoTrinhHocTap\\Java\\java06-swing\\lesson18_BaiTap_Nhom4\\src\\main\\java\\image\\VoLamTruyenKi\\volamtruyenkibackground.png")); // NOI18N
        getContentPane().add(lbBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStart;
    private javax.swing.JLabel lbBackgroundImage;
    private javax.swing.JLabel lbTeamDT;
    private javax.swing.JLabel lbTeamG;
    private javax.swing.JLabel lbTeamVL;
    // End of variables declaration//GEN-END:variables
}
