/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.WindowConstants;
import javax.swing.border.Border;

/**
 *
 * @author Admin
 */
public class Ex01Ui extends javax.swing.JFrame {

    private Border hightlightBorder;

    /**
     * Creates new form ui
     */
    public Ex01Ui(String title) {
        super(title);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
        initEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnTop = new javax.swing.JPanel();
        spTop = new javax.swing.JSplitPane();
        pnTopLeft = new javax.swing.JPanel();
        pnTopLeftTop = new javax.swing.JPanel();
        lbColor = new javax.swing.JLabel();
        pnTopLeftBottom = new javax.swing.JPanel();
        btRed = new javax.swing.JButton();
        btGreen = new javax.swing.JButton();
        btYellow = new javax.swing.JButton();
        btBlue = new javax.swing.JButton();
        pnTopRight = new javax.swing.JPanel();
        pnTopRightTop = new javax.swing.JPanel();
        lbSize = new javax.swing.JLabel();
        pnTopRightBottom = new javax.swing.JPanel();
        btReduction = new javax.swing.JButton();
        btIncrease = new javax.swing.JButton();
        pnBottom = new javax.swing.JPanel();
        pnBottomTop = new javax.swing.JPanel();
        lbColor2 = new javax.swing.JLabel();
        lbFontSize = new javax.swing.JLabel();
        pnBottomTextArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spTop.setDividerLocation(365);

        pnTopLeft.setMinimumSize(new java.awt.Dimension(200, 100));
        pnTopLeft.setPreferredSize(new java.awt.Dimension(500, 100));
        pnTopLeft.setLayout(new java.awt.BorderLayout());

        pnTopLeftTop.setBackground(new java.awt.Color(0, 153, 153));
        pnTopLeftTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 11));

        lbColor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbColor.setForeground(new java.awt.Color(255, 255, 255));
        lbColor.setText("Color Picker");
        pnTopLeftTop.add(lbColor);

        pnTopLeft.add(pnTopLeftTop, java.awt.BorderLayout.PAGE_START);

        pnTopLeftBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnTopLeftBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        btRed.setBackground(new java.awt.Color(255, 51, 51));
        btRed.setPreferredSize(new java.awt.Dimension(40, 40));
        pnTopLeftBottom.add(btRed);

        btGreen.setBackground(new java.awt.Color(0, 153, 153));
        btGreen.setPreferredSize(new java.awt.Dimension(40, 40));
        pnTopLeftBottom.add(btGreen);

        btYellow.setBackground(new java.awt.Color(255, 255, 51));
        btYellow.setPreferredSize(new java.awt.Dimension(40, 40));
        pnTopLeftBottom.add(btYellow);

        btBlue.setBackground(new java.awt.Color(0, 0, 204));
        btBlue.setPreferredSize(new java.awt.Dimension(40, 40));
        pnTopLeftBottom.add(btBlue);

        pnTopLeft.add(pnTopLeftBottom, java.awt.BorderLayout.CENTER);

        spTop.setLeftComponent(pnTopLeft);

        pnTopRight.setMinimumSize(new java.awt.Dimension(200, 100));
        pnTopRight.setPreferredSize(new java.awt.Dimension(200, 97));
        pnTopRight.setLayout(new java.awt.BorderLayout());

        pnTopRightTop.setBackground(new java.awt.Color(153, 153, 0));
        pnTopRightTop.setPreferredSize(new java.awt.Dimension(452, 46));
        pnTopRightTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 10));

        lbSize.setBackground(new java.awt.Color(153, 153, 0));
        lbSize.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbSize.setForeground(new java.awt.Color(255, 255, 255));
        lbSize.setText("Size: 18px");
        lbSize.setPreferredSize(new java.awt.Dimension(200, 24));
        pnTopRightTop.add(lbSize);

        pnTopRight.add(pnTopRightTop, java.awt.BorderLayout.PAGE_START);

        pnTopRightBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnTopRightBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        btReduction.setBackground(new java.awt.Color(102, 153, 0));
        btReduction.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btReduction.setText("Giảm");
        btReduction.setPreferredSize(new java.awt.Dimension(80, 40));
        pnTopRightBottom.add(btReduction);

        btIncrease.setBackground(new java.awt.Color(102, 153, 0));
        btIncrease.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btIncrease.setText("Tăng");
        btIncrease.setPreferredSize(new java.awt.Dimension(80, 40));
        pnTopRightBottom.add(btIncrease);

        pnTopRight.add(pnTopRightBottom, java.awt.BorderLayout.CENTER);

        spTop.setRightComponent(pnTopRight);

        javax.swing.GroupLayout pnTopLayout = new javax.swing.GroupLayout(pnTop);
        pnTop.setLayout(pnTopLayout);
        pnTopLayout.setHorizontalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        pnTopLayout.setVerticalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addComponent(spTop, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnTop, java.awt.BorderLayout.PAGE_START);

        pnBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnBottom.setLayout(new java.awt.BorderLayout());

        pnBottomTop.setBackground(new java.awt.Color(255, 255, 255));
        pnBottomTop.setPreferredSize(new java.awt.Dimension(500, 50));

        lbColor2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbColor2.setForeground(new java.awt.Color(0, 0, 0));
        lbColor2.setText("Color: red - ");

        lbFontSize.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbFontSize.setForeground(new java.awt.Color(0, 0, 0));
        lbFontSize.setText("Fontsize: 18px ");

        javax.swing.GroupLayout pnBottomTopLayout = new javax.swing.GroupLayout(pnBottomTop);
        pnBottomTop.setLayout(pnBottomTopLayout);
        pnBottomTopLayout.setHorizontalGroup(
            pnBottomTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottomTopLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbColor2)
                .addGap(0, 0, 0)
                .addComponent(lbFontSize))
        );
        pnBottomTopLayout.setVerticalGroup(
            pnBottomTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottomTopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnBottomTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbColor2)
                    .addComponent(lbFontSize))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnBottom.add(pnBottomTop, java.awt.BorderLayout.PAGE_START);

        text.setBackground(new java.awt.Color(255, 255, 255));
        text.setColumns(20);
        text.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 0, 0));
        text.setRows(5);
        text.setText("  Nội dung settings");
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout pnBottomTextAreaLayout = new javax.swing.GroupLayout(pnBottomTextArea);
        pnBottomTextArea.setLayout(pnBottomTextAreaLayout);
        pnBottomTextAreaLayout.setHorizontalGroup(
            pnBottomTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        pnBottomTextAreaLayout.setVerticalGroup(
            pnBottomTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottomTextAreaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnBottom.add(pnBottomTextArea, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnBottom, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initEvent() {
        btRedEvents();
        btGreenEvents();
        btYellowEvents();
        btBlueEvents();
        btReductionEvents();
        btIncreaseEvents();
    }

    private void btRedEvents() {
        btRed.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                text.setForeground(Color.RED);
                lbColor2.setText("Color: red - ");
            }
        });
    }

    private void btGreenEvents() {
        btGreen.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                text.setForeground(Color.GREEN);
                lbColor2.setText("Color: green - ");
            }
        });
    }

    private void btYellowEvents() {
        btYellow.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                text.setForeground(Color.YELLOW);
                lbColor2.setText("Color: yellow - ");
            }
        });
    }

    private void btBlueEvents() {
        btBlue.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                text.setForeground(Color.BLUE);
                lbColor2.setText("Color: blue - ");
            }
        });
    }

    private void btReductionEvents() {

        btReduction.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int size = text.getFont().getSize();
                if (size == -1) {
                    text.setFont(new Font("Tahoma", Font.BOLD, 0));
                } else {
                    lbSize.setText("Size: " + (size - 1) + "px");
                    lbFontSize.setText("Fontsize: " + (size - 1) + "px");
                    text.setFont(new Font("Tahoma", Font.BOLD, size - 1));

                }
            }
        });
    }

    private void btIncreaseEvents() {
        btIncrease.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int size = text.getFont().getSize();
                lbSize.setText("Size: " + (size + 1) + "px");
                lbFontSize.setText("Fontsize: " + (size + 1) + "px");
                text.setFont(new Font("Tahoma", Font.BOLD, size + 1));

            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex01Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex01Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex01Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex01Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex01Ui("Ex01").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBlue;
    private javax.swing.JButton btGreen;
    private javax.swing.JButton btIncrease;
    private javax.swing.JButton btRed;
    private javax.swing.JButton btReduction;
    private javax.swing.JButton btYellow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbColor;
    private javax.swing.JLabel lbColor2;
    private javax.swing.JLabel lbFontSize;
    private javax.swing.JLabel lbSize;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnBottomTextArea;
    private javax.swing.JPanel pnBottomTop;
    private javax.swing.JPanel pnTop;
    private javax.swing.JPanel pnTopLeft;
    private javax.swing.JPanel pnTopLeftBottom;
    private javax.swing.JPanel pnTopLeftTop;
    private javax.swing.JPanel pnTopRight;
    private javax.swing.JPanel pnTopRightBottom;
    private javax.swing.JPanel pnTopRightTop;
    private javax.swing.JSplitPane spTop;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables

}
