/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ui;

import connection.ConnectionManagerImpl;
import java.awt.Container;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Admin
 */
public class Ex02 extends javax.swing.JFrame {
    
    private Container container = getContentPane();
    private Connection connection;
    private ConnectionManagerImpl connectionProvider;
    PreparedStatement preparedStatement;
    private ResultSet resultSet;
    private HotelManager hotelManager;

    /**
     * Creates new form Ex02
     */
    public Ex02() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Ex02");
        initComponents();
        initEvent();
    }
    
    private void initEvent() {
        btLogin();
    }
    
    private void btLogin() {
        btLogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                btLoginEvent();
            }
            
        });
    }
    
    private void btLoginEvent() {
        if (tfUserName.getText().equals("") || tfPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
        } else {
            try {
                String query = "select *\n"
                        + "from nhanvien\n"
                        + "where TaiKhoan = ? and " + "MatKhau = ?";
                connectionProvider = new ConnectionManagerImpl();
                connection = connectionProvider.getConnection();
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, tfUserName.getText().toString());
                preparedStatement.setString(2, tfPassword.getText().toString());
                
                resultSet = preparedStatement.executeQuery();
                if (resultSet.next()) {
                    hotelManager = new HotelManager();
                    hotelManager.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!");
                }
                
            } catch (HeadlessException | SQLException e) {
            } finally {
                try {                    
                    preparedStatement.close();
                    resultSet.close();
                    connection.close();
                } catch (SQLException ex) {
                }
            }            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogin = new javax.swing.JButton();
        tfPassword = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        lbUserName = new javax.swing.JLabel();
        lbLoginFrom = new javax.swing.JLabel();
        lbBackgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLogin.setBackground(java.awt.Color.red);
        btLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btLogin.setText("LOGIN");
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 320, -1));

        tfPassword.setBackground(new java.awt.Color(255, 255, 255));
        tfPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(0, 0, 0));
        tfPassword.setPreferredSize(new java.awt.Dimension(76, 27));
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 320, 30));

        lbPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword.setText("Pasword");
        getContentPane().add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        tfUserName.setBackground(new java.awt.Color(255, 255, 255));
        tfUserName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfUserName.setForeground(new java.awt.Color(0, 0, 0));
        tfUserName.setPreferredSize(new java.awt.Dimension(76, 27));
        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 320, 30));

        lbUserName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setText("User Name");
        getContentPane().add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lbLoginFrom.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbLoginFrom.setForeground(new java.awt.Color(255, 255, 255));
        lbLoginFrom.setText("LOGIN  FROM");
        getContentPane().add(lbLoginFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        lbBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Background.png"))); // NOI18N
        getContentPane().add(lbBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserNameActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel lbBackgroud;
    private javax.swing.JLabel lbLoginFrom;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
